/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao.venda;

import DAO.ConnectionFactory;
import DAO.banco.BancoDAO;
import DAO.venda.ChequeDAO;
import DAO.venda.ParcelaDAO;
import DAO.venda.TipoPagamentoDAO;
import Modelo.banco.ModeloBanco;
import Modelo.venda.ModeloCheque;
import Modelo.venda.ModeloParcela;
import Modelo.venda.ModeloTipoPagamento;
import Visao.parcelas.Parcela;
import java.sql.Connection;
import java.sql.Date;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author E.B.O 2
 */
public class ChequeDialog extends javax.swing.JDialog {

    Parcela telaPai;

    /**
     * Creates new form ChequeDialog
     */
    public ChequeDialog(java.awt.Frame parent, boolean modal, Parcela telaPai, String idParcela) throws SQLException {
        super(parent, modal);
        initComponents();
        jTextFieldNumeroCheque.setEnabled(false);
        jTextFieldIdParcela.setText(idParcela);
        jTextFieldIdParcela.setEnabled(false);

        Connection connection = new ConnectionFactory().getConnection();

        BancoDAO bancoDAO = new BancoDAO(connection);
        TipoPagamentoDAO tipoPagamentoDAO = new TipoPagamentoDAO(connection);
        List<ModeloTipoPagamento> tipoPagamentos = tipoPagamentoDAO.lista();
        for (ModeloTipoPagamento mp : tipoPagamentos) {

            jComboBoxTipoPagamento.addItem(mp);
        }
        jComboBoxTipoPagamento.setSelectedIndex(0);

        List<ModeloBanco> bancos = bancoDAO.lista();
        for (ModeloBanco t : bancos) {
            jComboBoxBanco.addItem(t);
        }
        this.telaPai = telaPai;
        connection.close();

    }

    private ChequeDialog(JFrame jFrame, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldIdParcela = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNumeroCheque = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldValorCheque = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxBanco = new javax.swing.JComboBox<>();
        jButtonSalvar = new javax.swing.JButton();
        jComboBoxTipoPagamento = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jFormattedTextDataPagamento = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("E.B.O. Cheque");
        setMaximumSize(new java.awt.Dimension(500, 500));

        jLabel1.setText("ID Parcela");

        jLabel2.setText("Numedo do cheque");

        jTextFieldNumeroCheque.setText("0");

        jLabel3.setText("Valor");

        jLabel4.setText("Banco");

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jComboBoxTipoPagamento.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxTipoPagamentoItemStateChanged(evt);
            }
        });

        jLabel7.setText("Tipo de pagamento");

        try {
            jFormattedTextDataPagamento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel5.setText("Data Pagamento");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonSalvar)
                        .addGap(10, 10, 10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldNumeroCheque, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldValorCheque, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addComponent(jComboBoxTipoPagamento, 0, 166, Short.MAX_VALUE)
                            .addComponent(jLabel7)
                            .addComponent(jComboBoxBanco, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldIdParcela))
                            .addComponent(jLabel5)
                            .addComponent(jFormattedTextDataPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(443, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldIdParcela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jComboBoxTipoPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jFormattedTextDataPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNumeroCheque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldValorCheque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxBanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(jButtonSalvar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        try {
            Connection connection = new ConnectionFactory().getConnection();
            ParcelaDAO parcelaDAO = new ParcelaDAO(connection);
            ModeloParcela modeloParcela = parcelaDAO.buscaPorId(Long.parseLong(jTextFieldIdParcela.getText()));

            ModeloCheque modeloCheque = new ModeloCheque();
            ChequeDAO chequeDAO = new ChequeDAO(connection);
            ModeloTipoPagamento modeloTipoPagamento = (ModeloTipoPagamento) jComboBoxTipoPagamento.getSelectedItem();
            ModeloBanco modeloBanco = (ModeloBanco) jComboBoxBanco.getSelectedItem();
            modeloCheque.setIdTipoPagamento(modeloTipoPagamento.getId());
            modeloCheque.setIdparcela(Long.parseLong(jTextFieldIdParcela.getText()));
            modeloCheque.setNumeroCheque(jTextFieldNumeroCheque.getText());
            modeloCheque.setValor(Float.parseFloat(jTextFieldValorCheque.getText()));
            modeloCheque.setIdBanco(modeloBanco.getId());
            double total = parcelaDAO.SomaTotalValorPagoPorParcela(Long.parseLong(jTextFieldIdParcela.getText()));
            if (logica.LogicasPedido.validaData(jFormattedTextDataPagamento.getText())) {
                System.out.println(total + modeloCheque.getValor());
                if (modeloParcela.getValor().floatValue() < (total + modeloCheque.getValor())) {

                    JOptionPane.showMessageDialog(rootPane, "Valor invalido");
                } else {
                    
                    
                   
                SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");

                Date dataSalvar = new Date(format.parse(jFormattedTextDataPagamento.getText()).getTime());
                modeloCheque.setDatapaga(dataSalvar);
                
                    chequeDAO.adiciona(modeloCheque);
                }

            } else {
                JOptionPane.showMessageDialog(rootPane, "Data Invalida");
            }

            connection.close();
            
            this.telaPai.tranferenciaData(jFormattedTextDataPagamento.getText());

            dispose();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
            Logger.getLogger(ChequeDialog.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(ChequeDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            this.telaPai.preencherTabela();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
            Logger.getLogger(ChequeDialog.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jComboBoxTipoPagamentoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxTipoPagamentoItemStateChanged
        ModeloTipoPagamento modeloTipoPagamento = (ModeloTipoPagamento) jComboBoxTipoPagamento.getSelectedItem();

        if (modeloTipoPagamento.getId() == Long.parseLong("3")) {
            jTextFieldNumeroCheque.setEnabled(true);
        } else {
            jTextFieldNumeroCheque.setEnabled(false);
        }
    }//GEN-LAST:event_jComboBoxTipoPagamentoItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChequeDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChequeDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChequeDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChequeDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ChequeDialog dialog = new ChequeDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<Object> jComboBoxBanco;
    private javax.swing.JComboBox<Object> jComboBoxTipoPagamento;
    private javax.swing.JFormattedTextField jFormattedTextDataPagamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldIdParcela;
    private javax.swing.JTextField jTextFieldNumeroCheque;
    private javax.swing.JTextField jTextFieldValorCheque;
    // End of variables declaration//GEN-END:variables

}
