/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao.Fornecedor;

import DAO.fornecedor.FornecedorDAO;
import DAO.BairroDAO;
import DAO.CidadeDAO;
import DAO.ConnectionFactory;
import DAO.EstadoDAO;
import DAO.fornecedor.TipoFornecedorDAO;
import Modelo.Fornecedor.ModeloFornecedor;
import Modelo.Fornecedor.ModeloTipoFornecedor;
import Modelo.ModeloBairro;
import Modelo.ModeloCidades;
import Modelo.ModeloEstado;
import Visao.Endereco.FrmBairro;
import Visao.Endereco.FrmCidades;
import Visao.Endereco.FrmEstado;
import Visao.classificacoes.FormularioClassicificacao;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author SERVIDOR
 */
public class Fornecedor extends javax.swing.JFrame {

    /**
     * Creates new form Fornecedor
     */
    public Fornecedor() throws SQLException {
        initComponents();
        this.setLocationRelativeTo(null);
        jTextFieldID.setEnabled(false);

        ativaDesativaCampos(false);
        PreencherTabela();
        if (jComboBoxEstado.getItemCount() <= 0) {
            try {
                Connection connection = new ConnectionFactory().getConnection();
                EstadoDAO EstadoDao = new EstadoDAO(connection);
                ModeloEstado modeloEstado = new ModeloEstado();
                List<ModeloEstado> estado = EstadoDao.lista();

                for (ModeloEstado e : estado) {
                    jComboBoxEstado.addItem(e);
                }
                ModeloTipoFornecedor modeloTipoFornecedor = new ModeloTipoFornecedor();
                TipoFornecedorDAO tipoFornecedorDAO = new TipoFornecedorDAO(connection);
                List<ModeloTipoFornecedor> tipoFornecedors = tipoFornecedorDAO.lista();

                for (ModeloTipoFornecedor t : tipoFornecedors) {
                    jComboBoxTipofornecedor.addItem(t);
                }

            } catch (SQLException ex) {
                Logger.getLogger(Fornecedor.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldFantasia = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldEndereco = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldCnpj = new javax.swing.JTextField();
        jTextFieldTelefone = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldIncriçãoMunicipal = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldCelular = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldTelefone2 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextFieldFAX = new javax.swing.JTextField();
        jFormattedTextCEP = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        jComboBoxTipofornecedor = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaOBSERVAÇAO = new javax.swing.JTextArea();
        jButtonNovo = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        jButtonPesquisar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableFORNECEDOR = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jComboBoxEstado = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jComboBoxCidade = new javax.swing.JComboBox<>();
        jComboBoxBairro = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("E.B.O. Cadastro de Fornecedor ");

        jPanel1.setPreferredSize(new java.awt.Dimension(1099, 689));

        jLabel1.setText("ID");

        jLabel2.setText("Nome");

        jLabel3.setText("Fantasia");

        jLabel4.setText("Endereço");

        jLabel5.setText("CEP");

        jLabel6.setText("CNPJ");

        jLabel7.setText("Telefone");

        jLabel10.setText("Inscrição Municipal");

        jTextFieldIncriçãoMunicipal.setText("211231");

        jLabel14.setText("Celular");

        jTextFieldCelular.setText("3232123132");

        jLabel15.setText("Telefone Comercial");

        jTextFieldTelefone2.setText("321321231");

        jLabel19.setText("Fax");

        jTextFieldFAX.setText("2132123132132");

        try {
            jFormattedTextCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel13.setText("Tipo de Fornecedor");

        jLabel17.setText("Observação");

        jTextAreaOBSERVAÇAO.setColumns(20);
        jTextAreaOBSERVAÇAO.setRows(5);
        jTextAreaOBSERVAÇAO.setText("212312332");
        jTextAreaOBSERVAÇAO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextAreaOBSERVAÇAOMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTextAreaOBSERVAÇAO);

        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonAlterar.setText("Alterar");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jTableFORNECEDOR.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableFORNECEDOR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableFORNECEDORMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableFORNECEDOR);

        jLabel16.setText("Estado");

        jComboBoxEstado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxEstadoItemStateChanged(evt);
            }
        });

        jLabel12.setText("Cidade");

        jComboBoxCidade.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxCidadeItemStateChanged(evt);
            }
        });

        jComboBoxBairro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jComboBoxBairroMouseEntered(evt);
            }
        });
        jComboBoxBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxBairroActionPerformed(evt);
            }
        });

        jLabel11.setText("Bairro");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldFantasia)
                            .addComponent(jTextFieldNome)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jTextFieldTelefone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                            .addComponent(jTextFieldCnpj, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(15, 15, 15)
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(15, 15, 15)
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldTelefone2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(24, 24, 24)
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldFAX, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jFormattedTextCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(380, 380, 380)
                                                .addComponent(jLabel10)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextFieldIncriçãoMunicipal, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(72, 72, 72)
                                                .addComponent(jLabel13))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jComboBoxTipofornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jTextFieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(63, 63, 63)
                                                .addComponent(jLabel16)
                                                .addGap(10, 10, 10)
                                                .addComponent(jComboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(63, 63, 63)
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jComboBoxCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(77, 77, 77)
                                        .addComponent(jLabel11)
                                        .addGap(10, 10, 10)
                                        .addComponent(jComboBoxBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonNovo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonSalvar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonAlterar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonPesquisar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonExcluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonSair))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1012, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(jComboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(jComboBoxCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jFormattedTextCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(jComboBoxTipofornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextFieldCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jTextFieldIncriçãoMunicipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel19)
                            .addComponent(jTextFieldFAX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldTelefone2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNovo)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonAlterar)
                    .addComponent(jButtonPesquisar)
                    .addComponent(jButtonExcluir)
                    .addComponent(jButtonSair))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1087, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 711, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextAreaOBSERVAÇAOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextAreaOBSERVAÇAOMouseClicked

        //  lutar pelos direitos é uma coisa agora tudo é Machismo!O cara não baixa a tampa do vaso é machista o cara não bebe cerveja no copo é machista tudo é machismo!TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextAreaOBSERVAÇAOMouseClicked

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        ativaDesativaCampos(true);

        jTextFieldID.setText("");
        jTextFieldCnpj.setText("");
        jTextFieldIncriçãoMunicipal.setText("");
        jTextFieldIncriçãoMunicipal.setText("");
        jComboBoxTipofornecedor.setToolTipText("");
        jTextFieldNome.setText("");
        jTextFieldFantasia.setText("");
        jTextFieldEndereco.setText("");
        jComboBoxEstado.setToolTipText("");
        jComboBoxCidade.setToolTipText("");
        jComboBoxBairro.setToolTipText("");
        jTextFieldTelefone.setText("");
        jTextFieldTelefone2.setText("");
        jTextFieldCelular.setText("");
        jTextFieldFAX.setText("");
        jTextAreaOBSERVAÇAO.setText("");
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        ativaDesativaCampos(true);
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        try {
            FornecedorDAO fornecedorDAO = new FornecedorDAO(ConnectionFactory.getConnection());
            jTableFORNECEDOR.setModel(fornecedorDAO.buscaLike(jTextFieldNome.getText()));
            jTableFORNECEDOR.getColumnModel().getColumn(0).setPreferredWidth(5);
            jTableFORNECEDOR.getColumnModel().getColumn(0).setResizable(false);
            jTableFORNECEDOR.getColumnModel().getColumn(1).setPreferredWidth(5);
            jTableFORNECEDOR.getColumnModel().getColumn(1).setResizable(false);
            jTableFORNECEDOR.getColumnModel().getColumn(2).setPreferredWidth(20);
            jTableFORNECEDOR.getColumnModel().getColumn(2).setResizable(false);
            jTableFORNECEDOR.getColumnModel().getColumn(3).setPreferredWidth(20);
            jTableFORNECEDOR.getColumnModel().getColumn(3).setResizable(false);
            jTableFORNECEDOR.getColumnModel().getColumn(4).setPreferredWidth(20);
            jTableFORNECEDOR.getColumnModel().getColumn(4).setResizable(false);
            jTableFORNECEDOR.getColumnModel().getColumn(5).setPreferredWidth(20);
            jTableFORNECEDOR.getColumnModel().getColumn(5).setResizable(false);
            jTableFORNECEDOR.getColumnModel().getColumn(6).setPreferredWidth(20);
            jTableFORNECEDOR.getColumnModel().getColumn(6).setResizable(false);
            jTableFORNECEDOR.getColumnModel().getColumn(7).setPreferredWidth(20);
            jTableFORNECEDOR.getColumnModel().getColumn(7).setResizable(false);
            jTableFORNECEDOR.getColumnModel().getColumn(8).setPreferredWidth(20);
            jTableFORNECEDOR.getColumnModel().getColumn(8).setResizable(false);
            jTableFORNECEDOR.getTableHeader().setReorderingAllowed(false);

        } catch (SQLException ex) {
            Logger.getLogger(Fornecedor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        try {
            Connection connection = ConnectionFactory.getConnection();
            FornecedorDAO fornecedorDAO = new FornecedorDAO(connection);
            ModeloFornecedor modeloFornecedor = new ModeloFornecedor();
            modeloFornecedor.setId(Long.parseLong(jTextFieldID.getText()));

            fornecedorDAO.remove(modeloFornecedor);

            JOptionPane.showMessageDialog(rootPane, "Fornecedor excluido com Sucesso");

            PreencherTabela();//TODO add your handling code here:
            connection.close();
        } catch (SQLException ex) {
            JOptionPane.showConfirmDialog(rootPane, "Erro ao excluir os  Registro!!\n erro:" + ex);
        }

    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jTableFORNECEDORMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableFORNECEDORMouseClicked
        Long Id = Long.parseLong("" + jTableFORNECEDOR.getValueAt(jTableFORNECEDOR.getSelectedRow(), 0));        // TODO add your handling code here:

        Connection connection;
        try {
            connection = ConnectionFactory.getConnection();
            FornecedorDAO fornecedorDAO = new FornecedorDAO(connection);
            EstadoDAO estadoDAO = new EstadoDAO(connection);
            BairroDAO bairroDAO = new BairroDAO(connection);
            CidadeDAO cidadeDAO = new CidadeDAO(connection);
            TipoFornecedorDAO tipoFornecedorDAO = new TipoFornecedorDAO(connection);

            ModeloFornecedor modeloFornecedor = new ModeloFornecedor();
            modeloFornecedor = fornecedorDAO.buscaPorId(Id);

            ModeloTipoFornecedor modeloTipoFornecedor = new ModeloTipoFornecedor();
            modeloTipoFornecedor = tipoFornecedorDAO.buscaPorId(modeloFornecedor.getTipo());

            ModeloEstado modeloEstadoTabela = new ModeloEstado();
            modeloEstadoTabela = estadoDAO.buscaPorId(modeloFornecedor.getEstado());

            ModeloBairro modelobairroTabela = new ModeloBairro();
            modelobairroTabela = bairroDAO.buscaPorId(modeloFornecedor.getBairro());

            ModeloCidades modeloCidadeTabela = new ModeloCidades();
            modeloCidadeTabela = cidadeDAO.buscaPorId(modeloFornecedor.getCidade());

            //setar combobox
            for (int i = 0; i < jComboBoxEstado.getItemCount(); ++i) {

                ModeloEstado modeloEstadoTabela2 = (ModeloEstado) jComboBoxEstado.getItemAt(i);
                if (modeloEstadoTabela.getId().equals(modeloEstadoTabela2.getId())) {
                    jComboBoxEstado.setSelectedIndex(i);
                    break;

                }
            }

            for (int i = 0; i < jComboBoxCidade.getItemCount(); ++i) {
                ModeloCidades modeloCidades2 = (ModeloCidades) jComboBoxCidade.getItemAt(i);

                if (modeloCidadeTabela.getCodig().equals(modeloCidades2.getCodig())) {

                    jComboBoxCidade.setSelectedIndex(i);
                    break;

                }
            }

            for (int i = 0; i < jComboBoxBairro.getItemCount(); ++i) {
                ModeloBairro modeloBairro2 = (ModeloBairro) jComboBoxBairro.getItemAt(i);

                if (modelobairroTabela.getCodBairro().equals(modeloBairro2.getCodBairro())) {

                    jComboBoxBairro.setSelectedIndex(i);
                    break;

                }
            }

            for (int i = 0; i < jComboBoxTipofornecedor.getItemCount(); ++i) {
                ModeloTipoFornecedor modeloTipoFornecedorCombo = (ModeloTipoFornecedor) jComboBoxTipofornecedor.getItemAt(i);

                if (modeloTipoFornecedor.getId().equals(modeloTipoFornecedorCombo.getId())) {

                    jComboBoxTipofornecedor.setSelectedIndex(i);
                    break;

                }
            }

            jTextFieldCnpj.setText(modeloFornecedor.getCnpj());
            jFormattedTextCEP.setText(modeloFornecedor.getCep());
            jTextFieldIncriçãoMunicipal.setText(modeloFornecedor.getInscricaoMunicipal());

            jTextFieldNome.setText(modeloFornecedor.getNome());
            jTextFieldFantasia.setText(modeloFornecedor.getNomeFantasia());
            jTextFieldEndereco.setText(modeloFornecedor.getEndereco());

            jTextFieldTelefone.setText(modeloFornecedor.getTelefone());
            jTextFieldTelefone2.setText(modeloFornecedor.getTelefone1());
            jTextFieldCelular.setText(modeloFornecedor.getCelular());
            jTextFieldFAX.setText(modeloFornecedor.getFax());
            jTextAreaOBSERVAÇAO.setText(modeloFornecedor.getObservacao());

        } catch (SQLException ex) {
            Logger.getLogger(Fornecedor.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jTableFORNECEDORMouseClicked

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        try (Connection connection = ConnectionFactory.getConnection()) {
            FornecedorDAO fornecedorDAO = new FornecedorDAO(connection);// TODO add your handling code here   gta mor 98634.7205 //:
            CidadeDAO CidadeDao = new CidadeDAO(connection);
            TipoFornecedorDAO tipoFornecedorDAO = new TipoFornecedorDAO(connection);
            ModeloFornecedor modeloFornecedor = new ModeloFornecedor();

            //Tipofornecedor
            ModeloTipoFornecedor modeloTipoFornecedor = (ModeloTipoFornecedor) jComboBoxTipofornecedor.getSelectedItem();
            modeloFornecedor.setTipo(modeloTipoFornecedor.getId());
            //bairro
            ModeloBairro bairroCombo = (ModeloBairro) jComboBoxBairro.getSelectedItem();
            modeloFornecedor.setBairro(bairroCombo.getCodBairro());
            //cidade
            ModeloCidades cidadeCombo = (ModeloCidades) jComboBoxCidade.getSelectedItem();
            modeloFornecedor.setCidade(cidadeCombo.getCodig());
            //estado
            ModeloEstado estadoCombo = (ModeloEstado) jComboBoxEstado.getSelectedItem();
            modeloFornecedor.setEstado(estadoCombo.getId());

            modeloFornecedor.setNome(jTextFieldNome.getText().toUpperCase());

            modeloFornecedor.setEndereco(jTextFieldEndereco.getText().toUpperCase());
            modeloFornecedor.setCep(jFormattedTextCEP.getText().toUpperCase());
            modeloFornecedor.setTelefone1(jTextFieldTelefone.getText().toUpperCase());
            modeloFornecedor.setTelefone(jTextFieldTelefone2.getText().toUpperCase());
            modeloFornecedor.setFax(jTextFieldFAX.getText().toUpperCase());
            modeloFornecedor.setCelular(jTextFieldCelular.getText().toUpperCase());
            modeloFornecedor.setObservacao(jTextAreaOBSERVAÇAO.getText().toUpperCase());
            modeloFornecedor.setNomeFantasia(jTextFieldFantasia.getText().toUpperCase());
            modeloFornecedor.setCnpj(jTextFieldCnpj.getText().toUpperCase());
            modeloFornecedor.setInscricaoMunicipal(jTextFieldIncriçãoMunicipal.getText().toUpperCase());

            String idSalvar = jTextFieldID.getText();
            if (idSalvar.equals("")) {
                fornecedorDAO.adiciona(modeloFornecedor);

            } else {
                modeloFornecedor.setId(Long.parseLong(idSalvar));
                System.out.println(modeloFornecedor.getTipo());
                fornecedorDAO.altera(modeloFornecedor);

            }

            PreencherTabela();
            JOptionPane.showMessageDialog(rootPane, "Dados Inseridos Com Sucesso");

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, " Falha no Armazenamento de dados \n ERRO :" + ex);
        }
        jTextFieldID.setText("");

        jTextFieldCnpj.setText("");
        jTextFieldIncriçãoMunicipal.setText("");
        jTextFieldIncriçãoMunicipal.setText("");
        jComboBoxTipofornecedor.setToolTipText("");
        jTextFieldNome.setText("");
        jTextFieldFantasia.setText("");
        jTextFieldEndereco.setText("");
        jComboBoxEstado.setToolTipText("");
        jComboBoxCidade.setToolTipText("");
        jComboBoxBairro.setToolTipText("");
        jTextFieldTelefone.setText("");
        jTextFieldTelefone2.setText("");
        jTextFieldCelular.setText("");
        jTextFieldFAX.setText("");
        jTextAreaOBSERVAÇAO.setText("");
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jComboBoxEstadoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxEstadoItemStateChanged
        Connection connection = null;
        try {
            connection = new ConnectionFactory().getConnection();
        } catch (SQLException ex) {
            Logger.getLogger(Fornecedor.class.getName()).log(Level.SEVERE, null, ex);
        }

        CidadeDAO cidadeDAO = new CidadeDAO(connection);
        ModeloEstado estadoCombo = (ModeloEstado) jComboBoxEstado.getSelectedItem();
        List<ModeloCidades> cidadeCombo = cidadeDAO.buscaIdPorEstado(estadoCombo.getId());
        jComboBoxCidade.removeAllItems();

        for (ModeloCidades c : cidadeCombo) {
            jComboBoxCidade.addItem(c);
        }
    }//GEN-LAST:event_jComboBoxEstadoItemStateChanged

    private void jComboBoxCidadeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxCidadeItemStateChanged
        Connection connection = null;
        List<ModeloBairro> bairroCombo = null;

        try {
            connection = new ConnectionFactory().getConnection();
        } catch (SQLException ex) {
            Logger.getLogger(Fornecedor.class.getName()).log(Level.SEVERE, null, ex);
        }

        BairroDAO bairroDAO = new BairroDAO(connection);
        ModeloCidades cidadeCombo2 = (ModeloCidades) jComboBoxCidade.getSelectedItem();
        if (cidadeCombo2 != null) {
            bairroCombo = bairroDAO.buscaIdPorCidade(cidadeCombo2.getCodig());
        }

        jComboBoxBairro.removeAllItems();
        if (bairroCombo != null) {
            for (ModeloBairro b : bairroCombo) {
                jComboBoxBairro.addItem(b);
            }
        }
    }//GEN-LAST:event_jComboBoxCidadeItemStateChanged

    private void jComboBoxBairroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxBairroMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxBairroMouseEntered

    private void jComboBoxBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxBairroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Fornecedor().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Fornecedor.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    public void ativaDesativaCampos(boolean status) {
        if (status == false) {

            jTextFieldCnpj.setEnabled(false);
            jFormattedTextCEP.setEnabled(false);
            jTextFieldIncriçãoMunicipal.setEnabled(false);
            jComboBoxTipofornecedor.setEnabled(false);
            jTextFieldNome.setEnabled(false);
            jTextFieldFantasia.setEnabled(false);
            jTextFieldEndereco.setEnabled(false);
            jComboBoxEstado.setEnabled(false);
            jComboBoxCidade.setEnabled(false);
            jComboBoxBairro.setEnabled(false);
            jTextFieldTelefone.setEnabled(false);
            jTextFieldTelefone2.setEnabled(false);
            jTextFieldCelular.setEnabled(false);
            jTextFieldFAX.setEnabled(false);
            jTextAreaOBSERVAÇAO.setEnabled(false);

        } else if (status == true) {

            jTextFieldCnpj.setEnabled(true);
            jFormattedTextCEP.setEnabled(true);
            jTextFieldIncriçãoMunicipal.setEnabled(true);
            jComboBoxTipofornecedor.setEnabled(true);
            jTextFieldNome.setEnabled(true);
            jTextFieldFantasia.setEnabled(true);
            jTextFieldEndereco.setEnabled(true);
            jComboBoxEstado.setEnabled(true);
            jComboBoxCidade.setEnabled(true);
            jComboBoxBairro.setEnabled(true);
            jTextFieldTelefone.setEnabled(true);
            jTextFieldTelefone2.setEnabled(true);
            jTextFieldCelular.setEnabled(true);
            jTextFieldFAX.setEnabled(true);
            jTextAreaOBSERVAÇAO.setEnabled(true);

        }

    }

    public void PreencherTabela() throws SQLException {// preenchimento da tabela  ,  linhas e colunas , LuizDOURADO
        try (Connection connection = ConnectionFactory.getConnection()) {
            FornecedorDAO fornecedordao = new FornecedorDAO(connection);

            jTableFORNECEDOR.setModel(fornecedordao.listaTabela());
            jTableFORNECEDOR.getColumnModel().getColumn(0).setPreferredWidth(2);
            jTableFORNECEDOR.getColumnModel().getColumn(0).setResizable(false);
            jTableFORNECEDOR.getColumnModel().getColumn(1).setPreferredWidth(20);
            jTableFORNECEDOR.getColumnModel().getColumn(1).setResizable(false);
            jTableFORNECEDOR.getColumnModel().getColumn(2).setPreferredWidth(20);
            jTableFORNECEDOR.getColumnModel().getColumn(2).setResizable(false);
            jTableFORNECEDOR.getColumnModel().getColumn(3).setPreferredWidth(20);
            jTableFORNECEDOR.getColumnModel().getColumn(3).setResizable(false);
            jTableFORNECEDOR.getColumnModel().getColumn(4).setPreferredWidth(20);
            jTableFORNECEDOR.getColumnModel().getColumn(4).setResizable(false);
            jTableFORNECEDOR.getColumnModel().getColumn(5).setPreferredWidth(20);
            jTableFORNECEDOR.getColumnModel().getColumn(5).setResizable(false);
            jTableFORNECEDOR.getColumnModel().getColumn(6).setPreferredWidth(20);
            jTableFORNECEDOR.getColumnModel().getColumn(6).setResizable(false);
            jTableFORNECEDOR.getColumnModel().getColumn(7).setPreferredWidth(20);
            jTableFORNECEDOR.getColumnModel().getColumn(7).setResizable(false);
            jTableFORNECEDOR.getColumnModel().getColumn(8).setPreferredWidth(20);
            jTableFORNECEDOR.getColumnModel().getColumn(8).setResizable(false);

            jTableFORNECEDOR.getTableHeader().setReorderingAllowed(false);
            connection.close();
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<Object> jComboBoxBairro;
    private javax.swing.JComboBox<Object> jComboBoxCidade;
    private javax.swing.JComboBox<Object> jComboBoxEstado;
    private javax.swing.JComboBox<Object> jComboBoxTipofornecedor;
    private javax.swing.JFormattedTextField jFormattedTextCEP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableFORNECEDOR;
    private javax.swing.JTextArea jTextAreaOBSERVAÇAO;
    private javax.swing.JTextField jTextFieldCelular;
    private javax.swing.JTextField jTextFieldCnpj;
    private javax.swing.JTextField jTextFieldEndereco;
    private javax.swing.JTextField jTextFieldFAX;
    private javax.swing.JTextField jTextFieldFantasia;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldIncriçãoMunicipal;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldTelefone;
    private javax.swing.JTextField jTextFieldTelefone2;
    // End of variables declaration//GEN-END:variables

}
