/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao.Endereco;

import java.sql.SQLException;
import javax.swing.JOptionPane;

import DAO.CidadeDAO;
import DAO.ConnectionFactory;
import DAO.EstadoDAO;
import Modelo.ModeloEstado;
import java.sql.Connection;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Familia Nascimento
 */
public class FrmEstado extends javax.swing.JFrame {

    ModeloEstado modeloEstado = new ModeloEstado();

    /**
     * Creates new form FrmEstado
     */
    /**
     * Creates new form FrmEstado
     *
     * @throws java.sql.SQLException
     */
    public FrmEstado() throws SQLException {
        initComponents();
        List<ModeloEstado> estado = null;

        try {
            Connection connection = ConnectionFactory.getConnection();
            EstadoDAO EstadoDa = new EstadoDAO(connection);
            estado = EstadoDa.lista();
        } catch (SQLException ex) {
            Logger.getLogger(FrmEstado.class.getName()).log(Level.SEVERE, null, ex);
        }

        PreencherTabela();

    }

    public final void PreencherTabela() throws SQLException {

        try (Connection connection = ConnectionFactory.getConnection()) {
            EstadoDAO EstadoDao = new EstadoDAO(connection);
            jTableEstado.setModel(EstadoDao.listaTabela());
            jTableEstado.setRowSorter(new TableRowSorter( EstadoDao.listaTabela()));
            jTableEstado.getColumnModel().getColumn(0).setPreferredWidth(10);
            jTableEstado.getColumnModel().getColumn(0).setResizable(false);
            jTableEstado.getColumnModel().getColumn(1).setPreferredWidth(50);
            jTableEstado.getColumnModel().getColumn(1).setResizable(false);
            jTableEstado.getColumnModel().getColumn(2).setPreferredWidth(40);
            jTableEstado.getColumnModel().getColumn(2).setResizable(false);
            jTableEstado.getTableHeader().setReorderingAllowed(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jTextFieldNomeEstado = new javax.swing.JTextField();
        jButtonNovovo = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        jButtonPesquisar = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldSigla = new javax.swing.JTextField();
        jButtonSair = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEstado = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("E.B.O. Cadastro de Estados        ");
        setResizable(false);

        jLabel1.setText("ID");

        jLabel2.setText("Nome do Estado");

        jTextFieldCodigo.setEditable(false);
        jTextFieldCodigo.setBackground(new java.awt.Color(204, 204, 204));

        jButtonNovovo.setText("Novo");
        jButtonNovovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovovoActionPerformed(evt);
            }
        });

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonAlterar.setText("Alterar");
        jButtonAlterar.setEnabled(false);
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jButton5.setText("Excluir");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel3.setText("Sigla");

        jButtonSair.setText("SAIR");
        jButtonSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSairMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNomeEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldSigla, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonNovovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAlterar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonPesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSair)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldNomeEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldSigla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonAlterar)
                    .addComponent(jButtonPesquisar)
                    .addComponent(jButton5)
                    .addComponent(jButtonSair)
                    .addComponent(jButtonNovovo))
                .addContainerGap())
        );

        jTableEstado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableEstado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableEstadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableEstado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 11, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        jButtonAlterar.setEnabled(false);
        jButtonPesquisar.setEnabled(true);
        try {
            Connection connection = ConnectionFactory.getConnection();
            EstadoDAO estadoDao = new EstadoDAO(connection);

            if (validacao().isEmpty()) {
                modeloEstado.setNome(jTextFieldNomeEstado.getText().toUpperCase());
                modeloEstado.setSigla(jTextFieldSigla.getText().toUpperCase());
                estadoDao.adiciona(modeloEstado);
                JOptionPane.showMessageDialog(rootPane, "Dados Inseridos Com Sucesso");
                limpar();

            } else {
                String message = validacao();

                JOptionPane.showMessageDialog(null, message, "Aviso", JOptionPane.INFORMATION_MESSAGE);

            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
            Logger.getLogger(FrmEstado.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonNovovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovovoActionPerformed
        jTextFieldNomeEstado.setText("");
        jTextFieldSigla.setText("");
        jTextFieldCodigo.setText("");
        jButtonSalvar.setEnabled(true);
        jButtonAlterar.setEnabled(false);
        jButtonPesquisar.setEnabled(false);
// TODO add your handling code here:
    }//GEN-LAST:event_jButtonNovovoActionPerformed

    private void jButtonSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSairMouseClicked
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSairMouseClicked

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        jButtonAlterar.setEnabled(true);
        try {
            EstadoDAO estadoDAO = new EstadoDAO(ConnectionFactory.getConnection());

            jTableEstado.setModel(estadoDAO.buscaLike(jTextFieldNomeEstado.getText().toUpperCase()));
            jTableEstado.setRowSorter(new TableRowSorter( estadoDAO.buscaLike(jTextFieldNomeEstado.getText().toUpperCase())));
            jTableEstado.getColumnModel().getColumn(0).setPreferredWidth(10);
            jTableEstado.getColumnModel().getColumn(0).setResizable(false);
            jTableEstado.getColumnModel().getColumn(1).setPreferredWidth(50);
            jTableEstado.getColumnModel().getColumn(1).setResizable(false);
            jTableEstado.getColumnModel().getColumn(2).setPreferredWidth(40);
            jTableEstado.getColumnModel().getColumn(2).setResizable(false);
            jTableEstado.getTableHeader().setReorderingAllowed(false);// TODO add your handling code here:
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
            Logger.getLogger(FrmEstado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        Connection connection;
        try {
            connection = ConnectionFactory.getConnection(); // TODO add your handling code here:
            CidadeDAO CidadeDao = new CidadeDAO(connection);
            EstadoDAO EstadoDAO = new EstadoDAO(connection);
            if (validacao().isEmpty()) {
                modeloEstado.setId(Long.parseLong(jTextFieldCodigo.getText().toUpperCase()));
                modeloEstado.setNome(jTextFieldNomeEstado.getText().toUpperCase());
                modeloEstado.setSigla(jTextFieldSigla.getText().toUpperCase());
                EstadoDAO.altera(modeloEstado);
                limpar();
                JOptionPane.showMessageDialog(rootPane, "Dados Inseridos Com Sucesso");

            } else {
                String message = validacao();

                JOptionPane.showMessageDialog(null, message, "Aviso", JOptionPane.INFORMATION_MESSAGE);

            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
            Logger.getLogger(FrmEstado.class.getName()).log(Level.SEVERE, null, ex);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jTableEstadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableEstadoMouseClicked
        String Id_Estado = "" + jTableEstado.getValueAt(jTableEstado.getSelectedRow(), 0);
        String Nome_Estado = "" + jTableEstado.getValueAt(jTableEstado.getSelectedRow(), 1);
        String Sigla_Estado = "" + jTableEstado.getValueAt(jTableEstado.getSelectedRow(), 2);
        ModeloEstado ModeloEstado = new ModeloEstado();
        try {
            EstadoDAO EstadoDao = new EstadoDAO(ConnectionFactory.getConnection());
            jTextFieldCodigo.setText(Id_Estado);
            jTextFieldSigla.setText(Sigla_Estado);
            jTextFieldNomeEstado.setText(Nome_Estado);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
            Logger.getLogger(FrmEstado.class.getName()).log(Level.SEVERE, null, ex);
        }
        //              JOptionPane.showMessageDialog(rootPane,Nome_Estado);
// TODO add your handling code here:
    }//GEN-LAST:event_jTableEstadoMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            Connection connection = ConnectionFactory.getConnection();
            EstadoDAO EstadoDAO = new EstadoDAO(connection);
            ModeloEstado modeloEstado = new ModeloEstado();
            modeloEstado.setId(Long.parseLong(jTextFieldCodigo.getText()));

            EstadoDAO.remove(modeloEstado);
            JOptionPane.showMessageDialog(rootPane, "Estado excluido com Sucesso");

            PreencherTabela();//TODO add your handling code here:
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
            JOptionPane.showConfirmDialog(rootPane, "Erro ao excluir os  Registro!!\n erro:" + ex);
        }        // TODO ad            // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEstado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEstado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEstado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEstado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FrmEstado().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(FrmEstado.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonNovovo;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEstado;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldNomeEstado;
    private javax.swing.JTextField jTextFieldSigla;
    // End of variables declaration//GEN-END:variables
private String validacao() {
        String validar = "";

        int cont = 0;

        if (jTextFieldNomeEstado.getText().isEmpty()) {
            validar += "Cidade ";
            cont++;
        }
        if (jTextFieldSigla.getText().isEmpty()) {
            validar += "\nSigla ";
            cont++;
        }

        if (cont != 0) {
            validar = "Campos obrigatorios: \n" + validar;
        }
        return validar;
    }
    public void limpar(){
        jTextFieldCodigo.setText("");
        jTextFieldNomeEstado.setText("");
        jTextFieldSigla.setText("");
    }
}
